### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by iamadamreed** [stormpath/stormpath-aspnet#10] opened 2016-09-22 00:00 UTC
When creating a new project, and attempting to debug, Stormpath is forcing SSL, and when attempting to Debug via Chrome, without explicit setup https @ localhost isn't possible via Chrome.

**Comment by nbarbettini** [comment] 2016-09-22 14:50
Are you sure it's the Stormpath middleware that's forcing SSL? It's designed to work fine on either http or https. If you comment out the Stormpath middleware in Startup.cs, does the redirect behavior go away?

**Comment by iamadamreed** [comment] 2016-09-22 15:08
A new project will debug fine, but when I install Stormpath, it starts debugging as HTTPS.

**Comment by nbarbettini** [comment] 2016-10-09 03:51
@adamreed90 Do you have a repro project I can test? I haven't been able to reproduce this.

**Comment by nbarbettini** [comment] 2016-11-02 01:33
Ah, I wonder if it's related to this: https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/50

Are you using Visual Studio Code?

**Comment by nbarbettini** [comment] 2017-01-06 21:25
Closing this since I'm unable to repro. @adamreed90 if you can, please let me know!

**Closed as completed by nbarbettini** 2017-01-06 21:25 UTC
Labels: question
